# @package _global_

# defaults:
#   - reward_base

rewards:
  set_reward: jinrui
  set_reward_date: 20250810
  only_positive_rewards: False
  reward_scales:
      teleop_root_vel: 1.0
      teleop_anchor_body_position: 1.5
      teleop_anchor_body_rotation: 1.5
      local_key_body_position: 3.0
      local_key_body_rotation: 2.0
      key_body_velocity: 2.0
      key_body_ang_velocity: 2.0
      
      penalty_action_rate: -0.1
      penalty_dof_vel: -0.0001
      penalty_dof_acc: -3e-7
      foot_slip_penalty: -0.1
      limits_dof_pos: -10.0
      limits_torque: -5.0
      termination: -200.0
      collision: -30.0
      

  reward_tracking_sigma:
    local_key_body_pos: 0.1
    local_key_body_rot: 0.15
    key_body_vel: 1.0
    key_body_ang_vel: 10.0
    teleop_anchor_body_pos: 0.1
    teleop_anchor_body_rot: 0.15
    teleop_root_vel: 1.0

  adaptive_tracking_sigma:
    enable: False
    alpha: 1e-3
    type: mean # origin, mean, scale
    scale: 1.0

  desired_feet_air_time: 0.5

  reward_penalty_curriculum: False
  reward_initial_penalty_scale : 0.10
  reward_min_penalty_scale: 0.0
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 40
  reward_penalty_level_up_threshold: 42 
  reward_penalty_degree: 0.00001
  num_compute_average_epl: 10000

  reward_limit:
    soft_dof_pos_limit: 0.9
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.825

    reward_limits_curriculum:
      soft_dof_pos_curriculum: True
      soft_dof_pos_initial_limit: 0.95
      soft_dof_pos_max_limit: 0.95
      soft_dof_pos_min_limit: 0.95
      soft_dof_pos_curriculum_degree: 0.00000025
      soft_dof_pos_curriculum_level_down_threshold: 40
      soft_dof_pos_curriculum_level_up_threshold: 42

      soft_dof_vel_curriculum: True
      soft_dof_vel_initial_limit: 0.95
      soft_dof_vel_max_limit: 0.95
      soft_dof_vel_min_limit: 0.95
      soft_dof_vel_curriculum_degree: 0.00000025
      soft_dof_vel_curriculum_level_down_threshold: 40
      soft_dof_vel_curriculum_level_up_threshold: 42

      soft_torque_curriculum: True
      soft_torque_initial_limit: 0.85
      soft_torque_max_limit: 0.85
      soft_torque_min_limit: 0.85
      soft_torque_curriculum_degree: 0.00000025
      soft_torque_curriculum_level_down_threshold: 40
      soft_torque_curriculum_level_up_threshold: 42

  reward_penalty_reward_names : [
    "penalty_action_rate",
    "penalty_dof_vel",
    "penalty_dof_acc",
    "limits_dof_pos",
    "limits_torque",
    "foot_slip_penalty"
    ]